dokter1:
  voornaam: Frédéric
  achternaam: Goetghebuer
  afbeelding: dokter1.jpg


dokter2:
  voornaam: Evy
  achternaam: Luyten
  afbeelding: luyten.jpg


tel-text: 09/228.47.45
tel: +3292284745

straat: Land van Waaslaan 80
plaats: 9040 Sint-Amandsberg



title: Huisartsen Sint-Amandsberg
description: Huisartsen Sint-Amandsberg




# HIERONDER NIET AANKOMEN
###########################
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
# Disqus
discus-identifier: mr-brown # add your discus identifier
# Tracker
analytics: # Google Analytics
markdown: kramdown
plugins:
  - jekyll-sitemap
permalink: ':title/'

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
